@startuml Context
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Context

Person(user, "User", "User who interacts with the system")
System(learningSystem, "Learning System", "System that provides educational content")

Rel(user, learningSystem, "Uses")

@enduml
