spring:
  application:
    name: uplingo_resource_server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASEURL}
      chat:
        model: ${SPRING_AI_OLLAMA_CHAT_OPTIONS_MODEL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_SET_URI}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    ssl:
      trust: ${MAIL_HOST}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8081

cors:
  allowed-origin-web-client: ${CORS_ALLOWED_ORIGIN_WEB_CLIENT}