export enum StoryStatusEnum {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum GenreEnum {
  FANTASY = 'FANTASY',
  SCI_FI = 'SCI_FI',
  ROMANCE = 'ROMANCE',
  MYSTERY = 'MYSTERY',
  THRILLER = 'THRILLER',
  HORROR = 'HORROR',
  ADVENTURE = 'ADVENTURE',
  HISTORICAL = 'HISTORICAL',
  DRAMA = 'DRAMA',
  COMEDY = 'COMEDY',
  ACTION = 'ACTION',
  CRIME = 'CRIME',
  DETECTIVE = 'DETECTIVE',
  BIOGRAPHY = 'BIOGRAPHY',
  DYSTOPIAN = 'DYSTOPIAN',
  PARANORMAL = 'PARANORMAL',
  SUPERHERO = 'SUPERHERO',
  FAIRY_TALE = 'FAIRY_TALE',
  WESTERN = 'WESTERN',
  SPOOKY = 'SPOOKY',
}

export enum CharacterTypeEnum {
  MAIN = 'MAIN',
  SUPPORTING = 'SUPPORTING'
}
